### ISSUE TITLE
What is Intercom?

### ISSUE THREAD

**Issue by manel00** [stewwan/capacitor-intercom#1]
Hi, 

Cannot understand the idea of this plugin, can you put some description? more useful to know what i can do with it? Thanks

**Comment by davidseek** [comment]
Hey @manel00 

there is a new thing called www.google.com
Since you're a developer, this concept should not be sooooo new to you.
And a bit second of google combined with the provided links in the repo
would have told you, what intercom is....

https://www.intercom.com/
