### ISSUE TITLE
Feature Request: Update User

### ISSUE THREAD

**Issue by oliveready7** [stewwan/capacitor-intercom#12]
Hey is it possible to add the updateUser feature? 

`intercom.updateUser({
    custom_attributes: {
        paid_subscriber : true,
        monthly_spend: 155.5,
        team_mates: 3
    }
});`

https://developers.intercom.com/installing-intercom/docs/cordova-phonegap-configuration

Thanks!

**Comment by albalooshi** [comment]
Any updates on this?

**Comment by dv-alan** [comment]
We are being stalled from releasing updates because of this matter. Any updates please?

**Comment by stewwan** [comment]
@dv-alan no there’s no update. PR always welcomed.

**Comment by jongbonga** [comment]
Hi @stewwan I saw @atomassoni made a PR #13 that solve this request.
When can we expect a release?

**Comment by stewwan** [comment]
shipped in 2.1. thanks to @atomassoni

**Comment by jongbonga** [comment]
can we please have updated doc/readme for `updateUser` method
