### ISSUE TITLE
Use with capacitor-analytics

### ISSUE THREAD

**Issue by gusmarra** [stewwan/capacitor-intercom#14]
Hi Stewwan,

I have already implemented your plugin capacitor-analytics v0.0.4. Can I also use this for inAppMessages? Also is this plugin interfiring with Capacitor build in Push notification in any way?

Finally which version should I use If I have the 0.0.4 of analytics?

Thanks again

**Comment by stewwan** [comment]
> Can I also use this for inAppMessages? Also is this plugin interfiring with Capacitor build in Push notification in any way?

- No. But you can try to implement it directly on your app.

- Not that I know

v2+ plugins are for capacitor v2+
