### ISSUE TITLE
AndroidX issues with Intercom plugin

### ISSUE THREAD

**Issue by bot101** [stewwan/capacitor-intercom#15]
While attempting to build Capacitor app after adding the intercom plugin, I get the error below in Android Studio:

```
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-51:19 to override.
```
Similar issues on the internet suggest adding:
```
android.useAndroidX=true
android.enableJetifier=true
```
to the `build.gradle` file, but doing that throws a different error with AppCompat.

```
@capacitor\android\capacitor\src\main\java\com\getcapacitor\Plugin.java:9: error: cannot find symbol
import android.support.v4.app.ActivityCompat;
                             ^
  symbol:   class ActivityCompat
```

Any solution for this will be greatly appreciated, thanks.

**Comment by codeincontext** [comment]
That stack trace looks related to capacitor itself so you may want to look there. I think they have this covered in their docs now

**Comment by bot101** [comment]
Thanks @codeincontext, I was using an intercom version (latest) that will cause conflict with other plugins that are (AndroidX compliant). I fixed this by installing an older version of the plugin
