### ISSUE TITLE
non-static method getString(String,String) cannot be referenced from a static context

### ISSUE THREAD

**Issue by dannyconnolly** [stewwan/capacitor-intercom#18]
Hi,

We have an existing project that this error is happening on but I just installed a fresh ionic app and and added this plugin following the guide for android in your readme, but when I compile I get the same error as in the existing project.

I have included my keys from intercom in my capacitor.config.json and updated the MainActivity.java and checked that the keys are up to date.

Instructions to reproduce

`ionic start myApp tabs`

`npm install --save capacitor-intercom`

Add Android keys to capacitor.config.json

`npx cap add android`

`npx cap open android`

Update MainActivity.java

Run from android studio.

When trying to run the app from android studio the following errors appears when setting the appId and appKey.

`non-static method getString(String,String) cannot be referenced from a static context`

How can I resolve this issue or what am I doing wrong?

**Comment by stewwan** [comment]
Hello @dannyconnolly 

Can you check if it was fixed on latest 2.1.1?

Thanks for opening detailed issues like this 👍

**Comment by dannyconnolly** [comment]
Hi @stewwan I've updated to the latest version and no longer receive the error. Thank you for your quick reply. Keep up the good work.
