### ISSUE TITLE
Identity verification

### ISSUE THREAD

**Issue by davidseek** [stewwan/capacitor-intercom#2]
Hey guy,

first of all thanks for the project.
I have an active native iOS app in store and now reworking to 
have Android using Ionic.

I'm using Intercom's feature for identity verification.
Basically registering the user with a hash code.

https://app.intercom.io/a/apps/prokjmrn/settings/identity-verification/ios
https://developers.intercom.com/installing-intercom/docs/ios-identity-verification

`Intercom.setUserHash("your_hmac_of_user_id_or_email")`

Therefore I'm getting 401 Server response.
Can you please add an API for reg with hash or give instructions?

Thank you.

**Comment by stewwan** [comment]
Hey 👋

I’ll have a look, that’s prob something easy to add

**Comment by davidseek** [comment]
Hey @stewwan ,

appreciate it.

**Comment by davidseek** [comment]
Works perfect and I appreciate it very much.
